from reportlab.lib.pagesizes import letter, A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageTemplate, Frame, KeepTogether
from reportlab.lib.units import inch, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
import os
from datetime import datetime
from app.services.signal_tracker import SignalTracker
from app.services.ai_provider import OpenAIProvider

class ReportGenerator:
    def __init__(self):
        self.primary_color = colors.Color(0.1, 0.2, 0.4) # Dark Navy
        self.secondary_color = colors.Color(0.2, 0.6, 0.8) # Light Blue
        self.accent_color = colors.Color(0.9, 0.3, 0.1) # Orange Red
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        # Title Style
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=self.primary_color,
            alignment=TA_CENTER,
            spaceAfter=20
        ))
        
        # Section Header
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.white,
            backColor=self.primary_color,
            borderPadding=8,
            spaceBefore=12,
            spaceAfter=12,
            keepWithNext=True
        ))
        
        # Sub Header
        self.styles.add(ParagraphStyle(
            name='SubHeader',
            parent=self.styles['Heading3'],
            fontSize=14,
            textColor=self.secondary_color,
            spaceBefore=8,
            spaceAfter=8
        ))

        # Dashboard Label
        self.styles.add(ParagraphStyle(
            name='DashLabel',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.gray,
            alignment=TA_CENTER
        ))
        
        # Dashboard Value
        self.styles.add(ParagraphStyle(
            name='DashValue',
            parent=self.styles['Normal'],
            fontSize=12,
            fontName='Helvetica-Bold',
            textColor=colors.black,
            alignment=TA_CENTER
        ))

    def _header_footer(self, canvas, doc):
        canvas.saveState()
        canvas.setFont('Helvetica', 9)
        canvas.drawString(inch, 0.75 * inch, "Generated by BIAS-R-FnO | Market Sentiment & Analysis System")
        canvas.drawRightString(A4[0] - inch, 0.75 * inch, f"Page {doc.page}")
        
        # Header Line
        canvas.setStrokeColor(self.primary_color)
        canvas.setLineWidth(1)
        canvas.line(inch, A4[1] - 0.75 * inch, A4[0] - inch, A4[1] - 0.75 * inch)
        canvas.restoreState()

    def generate_pdf(self, report_data, is_weekly=False, name_prefix=None):
        signal_tracker = SignalTracker()
        
        # Ensure reports dir exists
        current_dir = os.path.dirname(os.path.abspath(__file__))
        project_root = os.path.dirname(os.path.dirname(os.path.dirname(current_dir)))
        reports_dir = os.path.join(project_root, 'reports')
        os.makedirs(reports_dir, exist_ok=True)
        
        symbol = report_data.get('symbol', 'UNKNOWN')
        timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
        
        if name_prefix:
            filename = f"{name_prefix}_{symbol}_{timestamp}.pdf"
        elif is_weekly:
            filename = f"weekly_report_{symbol}_{timestamp}.pdf"
        else:
            filename = f"report_{symbol}_{timestamp}.pdf"
        filepath = os.path.join(reports_dir, filename)
        
        doc = SimpleDocTemplate(filepath, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=50, bottomMargin=50)
        
        # Define Frame and Template
        frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id='normal')
        template = PageTemplate(id='test', frames=frame, onPage=self._header_footer)
        doc.addPageTemplates([template])
        
        story = []
        
        # --- TITLE SECTION ---
        story.append(Paragraph(f"{symbol} TRADING INTELLIGENCE", self.styles['ReportTitle']))
        story.append(Paragraph(f"Generated: {report_data.get('date')} | Timeframe: {report_data.get('timeframe', {}).get('chart_interval', '1 Day')}", self.styles['Normal']))
        story.append(Spacer(1, 20))
        
        # --- EXECUTIVE SUMMARY DASHBOARD ---
        ap = report_data.get('action_plan', {})
        decision = ap.get('decision', 'N/A')
        verdict = ap.get('verdict', 'Stay Flat')
        
        # Determine Status Color
        status_color = colors.grey
        if decision == "LONG": status_color = colors.green
        elif decision == "SHORT": status_color = colors.red
        elif decision == "RANGE TRADE": status_color = colors.blue
        elif decision == "NO TRADE": status_color = colors.orange
        
        # Create a dashboard table
        data = [
            [
                Paragraph("<b>ACTION SIGNAL</b>", self.styles['DashLabel']),
                Paragraph("<b>VERDICT</b>", self.styles['DashLabel']),
                Paragraph("<b>REGIME</b>", self.styles['DashLabel']),
                Paragraph("<b>CONFIDENCE</b>", self.styles['DashLabel'])
            ],
            [
                Paragraph(f"<font color='{status_color.hexval()}'><b>{decision}</b></font>", self.styles['DashValue']),
                Paragraph(f"<b>{verdict}</b>", self.styles['DashValue']),
                Paragraph(ap.get('regime', 'N/A'), self.styles['DashValue']),
                Paragraph(f"{ap.get('confidence', 0)}/100", self.styles['DashValue'])
            ]
        ]
        
        t = Table(data, colWidths=[doc.width/4]*4)
        t.setStyle(TableStyle([
            ('BOX', (0,0), (-1,-1), 1, colors.lightgrey),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.lightgrey),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BACKGROUND', (0,0), (-1,0), colors.whitesmoke),
            ('BOTTOMPADDING', (0,0), (-1,-1), 12),
            ('TOPPADDING', (0,0), (-1,-1), 12),
        ]))
        story.append(t)
        story.append(Spacer(1, 20))
        
        # --- DAILY MARKET SENTIMENT ---
        daily_sentiment = report_data.get('daily_sentiment')
        if daily_sentiment:
            story.append(Paragraph("Daily Market Sentiment (Pre-Market)", self.styles['SectionHeader']))
            
            sent_text = daily_sentiment.get('market_sentiment', 'Neutral')
            conf_score = daily_sentiment.get('confidence_score', 0)
            
            # Color logic
            sent_color = colors.blue
            if "Bullish" in sent_text: sent_color = colors.green
            elif "Bearish" in sent_text: sent_color = colors.red
            elif "Volatile" in sent_text: sent_color = colors.orange
            
            # Layout: Sentiment | Strategy
            sent_data = [
                [
                    Paragraph(f"<b>Market Bias:</b> <font color='{sent_color.hexval()}'>{sent_text}</font>", self.styles['Normal']),
                    Paragraph(f"<b>Confidence:</b> {conf_score}/100", self.styles['Normal'])
                ],
                [
                    Paragraph(f"<b>Strategy:</b> {daily_sentiment.get('trading_implication', {}).get('preferred_strategy', 'N/A')}", self.styles['Normal']),
                    Paragraph(f"<b>Avoid:</b> {daily_sentiment.get('trading_implication', {}).get('avoid', 'N/A')}", self.styles['Normal'])
                ]
            ]
            
            st = Table(sent_data, colWidths=[doc.width/2, doc.width/2])
            st.setStyle(TableStyle([
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('LINEBELOW', (0,0), (-1,0), 0.5, colors.lightgrey),
                ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ]))
            story.append(st)
            story.append(Spacer(1, 10))
            
            # Factors
            factors = daily_sentiment.get('supporting_factors', [])
            if factors:
                story.append(Paragraph("<b>Driving Factors:</b>", self.styles['SubHeader']))
                for f in factors:
                    story.append(Paragraph(f"• {f}", self.styles['Normal'], bulletText="•"))
        
        story.append(Spacer(1, 15))

        # --- CHART SECTION ---
        chart_path = report_data.get('chart_path')
        if chart_path and os.path.exists(chart_path):
            story.append(Paragraph("Technical Analysis Chart", self.styles['SectionHeader']))
            img = Image(chart_path, width=450, height=300) # Maintain aspect ratio roughly
            story.append(img)
            story.append(Spacer(1, 15))

        # --- TRADE SETUP & LOGIC ---
        story.append(Paragraph("Trade Setup & Logic", self.styles['SectionHeader']))
        
        indicators = report_data.get('indicators', {})
        sr = report_data.get('support_resistance', {})
        pivots = ap.get('pivots', {})
        
        # Setup Table
        setup_data = [
            ["Parameter", "Value", "Condition"],
            ["Current Price", f"₹{indicators.get('current_price', 'N/A')}", "-"],
            ["Intraday Pivot", f"₹{pivots.get('pivot', 'N/A')}" if pivots else "N/A", "Magnet Level"],
            ["Exec. Resistance (R1)", f"₹{pivots.get('r1', 'N/A')}" if pivots else "N/A", "Intraday Sell Zone"],
            ["Exec. Support (S1)", f"₹{pivots.get('s1', 'N/A')}" if pivots else "N/A", "Intraday Buy Zone"],
            ["Context Resistance", f"₹{sr.get('resistance', 'N/A')}", "Daily Breakout Level"],
            ["Context Support", f"₹{sr.get('support', 'N/A')}", "Daily Breakdown Level"],
            ["ADX (Strength)", f"{indicators.get('adx', 'N/A')}", "Target > 20"],
            ["RSI (Momentum)", f"{indicators.get('rsi', 'N/A')}", "30 < RSI < 70"]
        ]
        
        setup_table = Table(setup_data, colWidths=[doc.width/3]*3)
        setup_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('ALIGN', (1,0), (-1,-1), 'CENTER'),
        ]))
        story.append(setup_table)
        story.append(Spacer(1, 10))
        
        if decision in ["LONG", "SHORT", "RANGE TRADE"]:
            story.append(Paragraph("🎯 EXECUTABLE PLAN", self.styles['SubHeader']))
            plan_text = f"""
            <b>STRATEGY:</b> {verdict}<br/>
            <b>RECOMMENDED STRIKES:</b> {ap.get('strikes', 'N/A')}<br/>
            <b>ENTRY ZONE:</b> {ap.get('entry_condition', 'N/A')}<br/>
            <b>STOP LOSS:</b> ₹{ap.get('stop_loss', 'N/A')} (Strict)<br/>
            <b>TARGETS:</b> ₹{ap.get('target_1', 'N/A')} / ₹{ap.get('target_2', 'N/A')}<br/>
            <b>INVALIDATION:</b> {ap.get('invalidation', 'N/A')}
            """
            p = Paragraph(plan_text, self.styles['Normal'])
            # Put in a box
            t_plan = Table([[p]], colWidths=[doc.width])
            t_plan.setStyle(TableStyle([
                ('BOX', (0,0), (-1,-1), 2, status_color),
                ('BACKGROUND', (0,0), (-1,-1), colors.whitesmoke),
                ('PADDING', (0,0), (-1,-1), 10)
            ]))
            story.append(t_plan)
        else:
            story.append(Paragraph("⏳ WAITING PLAN", self.styles['SubHeader']))
            wait_text = f"Wait for price to break ₹{sr.get('resistance', 'N/A')} (Long) or ₹{sr.get('support', 'N/A')} (Short) with expanding volume."
            story.append(Paragraph(wait_text, self.styles['Normal']))

        story.append(Spacer(1, 15))

        # --- AI COMMENTARY ---
        try:
            ai = OpenAIProvider()
            ai_text = ai.explain_report(report_data)
            if ai_text:
                story.append(Paragraph("AI Analyst Commentary", self.styles['SectionHeader']))
                story.append(Paragraph(ai_text, self.styles['Normal']))
                story.append(Spacer(1, 15))
        except Exception:
            pass

        # --- RISK MANAGEMENT ---
        story.append(Paragraph("Risk Management", self.styles['SectionHeader']))
        ps = report_data.get('position_sizing', {})
        rc = report_data.get('risk_context', {})
        
        risk_text = f"""
        <b>Volatility (ATR):</b> ₹{rc.get('atr', 'N/A')} ({rc.get('atr_percentage', 'N/A')}% of price)<br/>
        <b>Position Sizing:</b> {ps.get('advice', 'N/A')}<br/>
        <b>Max Risk Per Trade:</b> 1-2% of Capital Recommended.
        """
        story.append(Paragraph(risk_text, self.styles['Normal']))
        story.append(Spacer(1, 20))
        
        # Disclaimer
        story.append(Paragraph("Disclaimer: This report is for educational purposes only. Trading involves risk.", self.styles['DashLabel']))
        
        # Log
        signal_tracker.log_signal(symbol, decision, indicators.get('current_price', 'N/A'), report_data.get('date'))
        
        doc.build(story)
        return filepath
